### ISSUE TITLE
naive_bayes undefined prior

### ISSUE THREAD

**Issue by Zimamazim** [ufal/npfl129#118]
In task naive_bayes there isn't defined which prior distribution should be used. When solving the task, I assumed we are using uniform prior distribution. However it was distribution based on frequencies of classes in train data. The difference is really small, doesn't influence the result significantly most of the time and is hard to debug. Mentioning explicitly which prior distribution is used in assignment would be really helpful. Thanks

**Comment by foxik** [comment]
The only information about it is on the slide https://ufal.mff.cuni.cz/~straka/courses/npfl129/2122/slides/?08#70, where there is

> Therefore, instead of modeling p(C_k∣x) we model the prior p(C_k) and the distribution p(x∣C_k).

where the part "model the prior p(C_k)" is almost always modeled according to the training data classes distribution (it is difficult to come with a different distribution).

I have nevertheless added a note on the slides in 0d25a4e and in the template in 361903a; a community-work point is yours.

Cheers :-)
