### ISSUE TITLE
MLP weights initialization value doubt

### ISSUE THREAD

**Issue by akumm2k** [ufal/npfl129#146]
https://github.com/ufal/npfl129/blob/ca5cef81cded8f3111cae08c93aca9f4e99ecb11/slides/04/04.md?plain=1#L548-L550

> $M$ is the size of the layer computed by the corresponding edge 

Is $M$ just the size of the layer, whose "inputs" we compute by using the corresponding weights? 
It is not clear to me how a "corresponding edge" would computer the size of the layer. Could you please clarify?

How does the aforementioned fact relate to the initialization of `low` and `high` in the following assignment?

https://github.com/ufal/npfl129/blob/ca5cef81cded8f3111cae08c93aca9f4e99ecb11/labs/04/mlp_classification_sgd.py#L35-L37

Thank you!

**Comment by foxik** [comment]
Hi,

thanks, the formulation was definitely incorrect; what I meant is "the size of the target layer", i.e., "the size size of the layer, whose element is computed by the corresponding edge".

I tried to improve the slide in f4086e2676, see https://ufal.mff.cuni.cz/~straka/courses/npfl129/2223/slides/?04#88.
- I now talk about whole weight matrices and the sizes of the layers they process;
- I changed the meaning of $M$ -- it is now the size of the source layer (that is more consistent with https://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf);
- I also added  the information that the exact range becomes more important for deeper networks.

Now the dominant initialization is either Glorot initialization (the one in the above paper), which uses $\pm\sqrt{\frac{6}{M+O}}$ range boundary, or He initialization (https://arxiv.org/abs/1502.01852), which uses $\pm\sqrt{\frac{6}{M}}$; see the respective papers for details.

The $[-0.1, 0.1]$ range in the template is a range which is "roughly correct" corresponding to the formula on the slides -- for a network with the 64 inputs it should be $[-0.125, 0.125]$ and for e.g. 50 hidden units it is ~ $[-0.141, 0.141]$. (For the latter two initialization schemes our $[-0.1, 0.1]$ range is a bit too small, but for a single hidden layer the impact is quite small.)
