### ISSUE TITLE
Double heading

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/npfl129#220]
i would create a pull request but i did not want to fork the repo..

These two lines should be deleted:
https://github.com/ufal/npfl129/blob/e855f33a7c1db58c9d1dccc7aae6cf672bc5ff04/slides/04/04.md?plain=1#L416
https://github.com/ufal/npfl129/blob/e855f33a7c1db58c9d1dccc7aae6cf672bc5ff04/slides/04/04.md?plain=1#L435

**Comment by foxik** [comment]
When I was writing it, it was deliberate -- I wanted this to be both in the title of the slide and also as the black color heading in the white part of the slides (I think people do not read titles that too much); so if the bullet points are examples of output layer activation functions, I deliberiately repeated it. But it is now up to @jlibovicky to decide what he likes :grin:
