### ISSUE TITLE
notation of crossentropy and joint entropy

### ISSUE THREAD

**Issue by adam-osusky** [ufal/npfl129#221]
In the lecture slides `slides/03/03.md` the crossentropy is notated H(X,Y). But later in `slides/06/06.md` is used a visualization of mutual information where is H(X, Y) notation for joint entropy. 

It is little bit misleading because crossentropy is not visualized on that picture. If in fact the visualization is for crossentropy then I am sorry for my lack of understanding.

**Comment by foxik** [comment]
Hi,

you are right, but unfortunately, cross-entropy and joint entropy have the same notation. I have modified the figure in slides of the lecture 6 to explicitly state that joint entropy is meant, see https://ufal.mff.cuni.cz/~courses/npfl129/2324/slides/?06#28 (you might need to clear image cache if you see the original image). Thanks!
