### ISSUE TITLE
Zlepšení efektivity labs/01/linear_regression_features.py

### ISSUE THREAD

**Issue by b0r3k** [ufal/npfl129#85]
Nebylo by z hlediska efektivity lepší vytvořit si na začátku programu jednu matici pro všechna data, pak jednou projít všechny mocniny a zaplnit sloupce matice, a pak v daném průchodu smyčky si již jen jako data vybírat relevantní část matice?
Vzhledem k tomu, že aktuálně předmět neběží, přidám kód:
```
    # Create the data matrix of known size
    data = np.zeros([np.shape(xs)[0], args.range])

    # Fill all the needed data once
    for power in range(1, args.range + 1):
        data[:, power - 1] = np.power(xs, power)

    rmses = []
    for order in range(1, args.range + 1):
        # Take part of the data important for this step
        current_data = data[:, :order]
        
        # TODO: Split the data into a train set and a test set.
```

**Comment by foxik** [comment]
Určitě to efektivnější je; ale šablona takové řešení určitě nevylučuje, takže pokud si to někdo předpočítá a pak jen zaindexuje, tak určitě projde; ale stejně tak projde i řešení, které rysy vytváří pokaždé znova (nebo přikonkatenuje k rysům z minulé iterace), a stejně, když se to spočítá celé (což je zamýšlené, nezáleží mi moc na tom, jak přesně se ty rysy vytvoří).

Jinak to, že předmět právě neběží, nic moc neznamená -- issues v repository jsou napořád, takže tady budou i až předmět poběží :-) Ale tenhle zdroják se v pořádku, není v něm nic světoborného.

Srdečně zdravím,
Milan S.
