### ISSUE TITLE
Confusing notation for gradients

### ISSUE THREAD

**Issue by Rattko** [ufal/npfl129#87]
Hello!

The notation you introduced for gradients in the first lecture may be a little bit confusing.

<img src="https://render.githubusercontent.com/render/math?math=\nabla_{x}f"> is usually used for [directional derivatives](https://en.wikipedia.org/wiki/Directional_derivative) in the direction of x. I believe, it would be better to use <img src="https://render.githubusercontent.com/render/math?math=\nabla f(x)"> as it is the usual notation for [gradients](https://en.wikipedia.org/wiki/Gradient) evaluated at a given point.

Note: The LaTex symbols may not render properly when using dark themes. GitHub doesn't natively support LaTex in issues, so this is a bit hacky solution.

**Comment by foxik** [comment]
Hi,

there are two points here:
- I definitely forgot to add the point where the gradient should be evaluated; I fixed that in 9d2e5cb5b88f77e
- however, the notation with the subscript (a vector of variables whose partial derivative is computed) is used in ML regularly - see for example the Adam paper (the optimizer used most frequently in deep learning) Algorithm 1 https://arxiv.org/pdf/1412.6980.pdf, or for example the Deep learning book notation https://www.deeplearningbook.org/contents/notation.html .

So I am keeping the subscript, but adding the point where to evaluate the gradient. Also, that is a community_work point for you ;-)

Cheers.
